name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install libpcap
      run: |
        sudo apt-get update
        sudo apt-get install -y libpcap-dev

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: golangci-lint
      continue-on-error: true
      uses: golangci/golangci-lint-action@v2
      with:
        # Required
        version: v1.38
